[package]
name = "chapter_1"
version = "0.0.0"
authors = ["YOU!"]

[dependencies]
# Do you _really_ need to put anything here? :)
#
# Try to write it with just standard library, ask for help if you need it.
